import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

@Injectable()
export class PdfService {
  async generateContract(data: any): Promise<Buffer> {
    const doc = new PDFDocument();
    const buffers: Buffer[] = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => {});

    doc.fontSize(20).text('Speaker Booking Contract', { align: 'center' });
    doc.moveDown();
    doc.text(`Speaker: ${data.speakerName}`);
    doc.text(`Business: ${data.businessName}`);
    doc.text(`Event: ${data.eventDetails}`);
    doc.text(`Date: ${data.date}`);
    doc.text(`\n\nThis agreement was auto-generated by NextSpeech.`);

    doc.end();

    return new Promise((resolve) => {
      doc.on('end', () => {
        resolve(Buffer.concat(buffers));
      });
    });
  }
}
